### ISSUE TITLE
List of Service

### ISSUE THREAD

**Issue by Saeed-L5** [Saeed-L5/dream-events#1]
**Acceptance Criteria**

- [x] - The homepage displays a list of our service events.
- [x] - The list is responsive and looks good on all main device sizes.

**Tasks**

- [x] - Add an HTML section on the homepage.
- [x] - Style the event list using Bootstrap.
- [x] - Add some sample events including event name, and brief description.
