### ISSUE TITLE
Past events photos

### ISSUE THREAD

**Issue by Saeed-L5** [Saeed-L5/dream-events#2]
**Acceptance Criteria**

- [x] - The events page  displays a section with photos from past events
- [x] -Our Events is responsive and looks good on all main device sizes.

**Tasks**

- [x] - Add a section on the event page for photos from past events.
- [x] - Populate the our event with sample photos from past events.
- [x] - Apply Bootstrap classes to create a visually appealing layout for the photo gallery.
